-- MySQL Script generated by MySQL Workbench
-- Thu Jun  9 16:26:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema unjarall_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unjarall_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unjarall_db` DEFAULT CHARACTER SET utf8 ;
USE `unjarall_db` ;

-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_leagues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_leagues` (
  `lid` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`lid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_teams` (
  `tid` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `tb_leagues_lid` INT NOT NULL,
  PRIMARY KEY (`tid`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_tb_teams_tb_leagues_idx` (`tb_leagues_lid` ASC),
  CONSTRAINT `fk_tb_teams_tb_leagues`
    FOREIGN KEY (`tb_leagues_lid`)
    REFERENCES `unjarall_db`.`tb_leagues` (`lid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_players` (
  `pid` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NULL,
  `height` INT NULL,
  `weight` INT NULL,
  `tb_teams_tid` INT NOT NULL,
  PRIMARY KEY (`pid`),
  INDEX `fk_tb_players_tb_teams1_idx` (`tb_teams_tid` ASC),
  CONSTRAINT `fk_tb_players_tb_teams1`
    FOREIGN KEY (`tb_teams_tid`)
    REFERENCES `unjarall_db`.`tb_teams` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_stats` (
  `sid` INT NOT NULL,
  `goals` INT NULL,
  `appearances` INT NULL,
  `assists` INT NULL,
  `tb_players_pid` INT NOT NULL,
  `season` VARCHAR(45) NULL,
  `passes` INT NULL,
  `shots` INT NULL,
  `teams` VARCHAR(300) NULL,
  PRIMARY KEY (`sid`),
  INDEX `fk_tb_stats_tb_players1_idx` (`tb_players_pid` ASC),
  CONSTRAINT `fk_tb_stats_tb_players1`
    FOREIGN KEY (`tb_players_pid`)
    REFERENCES `unjarall_db`.`tb_players` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_game_teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_game_teams` (
  `gtid` INT NOT NULL,
  `players` VARCHAR(200) NOT NULL,
  `collection_point` INT NOT NULL,
  `game_league` TINYINT(5) NULL,
  PRIMARY KEY (`gtid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_users` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `id` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `profile_img` VARCHAR(45) NULL,
  `tb_game_teams_gtid` INT NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tb_users_tb_game_teams1_idx` (`tb_game_teams_gtid` ASC),
  CONSTRAINT `fk_tb_users_tb_game_teams1`
    FOREIGN KEY (`tb_game_teams_gtid`)
    REFERENCES `unjarall_db`.`tb_game_teams` (`gtid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_boards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_boards` (
  `bid` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` VARCHAR(200) NOT NULL,
  `create_time` DATE NOT NULL,
  `edit_time` DATE NULL,
  `tb_users_uid` INT NOT NULL,
  PRIMARY KEY (`bid`),
  INDEX `fk_tb_boards_tb_users1_idx` (`tb_users_uid` ASC),
  CONSTRAINT `fk_tb_boards_tb_users1`
    FOREIGN KEY (`tb_users_uid`)
    REFERENCES `unjarall_db`.`tb_users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_comments` (
  `cid` INT NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `create_time` DATE NULL,
  `edit_time` DATE NULL,
  `tb_boards_bid` INT NOT NULL,
  PRIMARY KEY (`cid`),
  INDEX `fk_tb_comments_tb_boards1_idx` (`tb_boards_bid` ASC),
  CONSTRAINT `fk_tb_comments_tb_boards1`
    FOREIGN KEY (`tb_boards_bid`)
    REFERENCES `unjarall_db`.`tb_boards` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_player_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_player_comments` (
  `pcid` INT NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `content` VARCHAR(200) NOT NULL,
  `create_time` DATE NOT NULL,
  `edit_time` DATE NOT NULL,
  `tb_players_pid` INT NOT NULL,
  PRIMARY KEY (`pcid`),
  INDEX `fk_tb_player_comments_tb_players1_idx` (`tb_players_pid` ASC),
  CONSTRAINT `fk_tb_player_comments_tb_players1`
    FOREIGN KEY (`tb_players_pid`)
    REFERENCES `unjarall_db`.`tb_players` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_team_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_team_comments` (
  `tcid` INT NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `content` VARCHAR(200) NOT NULL,
  `create_time` DATE NOT NULL,
  `edit_time` DATE NOT NULL,
  `tb_teams_tid` INT NOT NULL,
  PRIMARY KEY (`tcid`),
  INDEX `fk_tb_team_comments_tb_teams1_idx` (`tb_teams_tid` ASC),
  CONSTRAINT `fk_tb_team_comments_tb_teams1`
    FOREIGN KEY (`tb_teams_tid`)
    REFERENCES `unjarall_db`.`tb_teams` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_team_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_team_likes` (
  `tlid` INT NOT NULL AUTO_INCREMENT,
  `cnt` INT NULL DEFAULT 0,
  `tb_teams_tid` INT NOT NULL,
  INDEX `fk_tb_team_likes_tb_teams1_idx` (`tb_teams_tid` ASC),
  PRIMARY KEY (`tlid`),
  CONSTRAINT `fk_tb_team_likes_tb_teams1`
    FOREIGN KEY (`tb_teams_tid`)
    REFERENCES `unjarall_db`.`tb_teams` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_player_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_player_likes` (
  `plid` INT NOT NULL AUTO_INCREMENT,
  `cnt` INT NULL DEFAULT 0,
  `tb_players_pid` INT NOT NULL,
  INDEX `fk_tb_player_likes_tb_players1_idx` (`tb_players_pid` ASC),
  PRIMARY KEY (`plid`),
  CONSTRAINT `fk_tb_player_likes_tb_players1`
    FOREIGN KEY (`tb_players_pid`)
    REFERENCES `unjarall_db`.`tb_players` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_game_computer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_game_computer` (
  `gcid` INT NOT NULL,
  `squard` VARCHAR(200) NULL,
  PRIMARY KEY (`gcid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_comment_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_comment_comments` (
  `ccid` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(200) NULL,
  `author` VARCHAR(45) NULL,
  `create_time` DATE NULL,
  `edit_time` DATE NULL,
  `tb_comments_cid` INT NOT NULL,
  PRIMARY KEY (`ccid`),
  INDEX `fk_tb_comment_comments_tb_comments1_idx` (`tb_comments_cid` ASC),
  CONSTRAINT `fk_tb_comment_comments_tb_comments1`
    FOREIGN KEY (`tb_comments_cid`)
    REFERENCES `unjarall_db`.`tb_comments` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_board_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_board_likes` (
  `blid` INT NOT NULL AUTO_INCREMENT,
  `cnt` INT NULL DEFAULT 0,
  `tb_boards_bid` INT NOT NULL,
  PRIMARY KEY (`blid`),
  INDEX `fk_tb_board_likes_tb_boards1_idx` (`tb_boards_bid` ASC),
  CONSTRAINT `fk_tb_board_likes_tb_boards1`
    FOREIGN KEY (`tb_boards_bid`)
    REFERENCES `unjarall_db`.`tb_boards` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_board_dislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_board_dislikes` (
  `bdid` INT NOT NULL AUTO_INCREMENT,
  `cnt` INT NULL DEFAULT 0,
  `tb_boards_bid` INT NOT NULL,
  PRIMARY KEY (`bdid`),
  INDEX `fk_tb_board_dislikes_tb_boards1_idx` (`tb_boards_bid` ASC),
  CONSTRAINT `fk_tb_board_dislikes_tb_boards1`
    FOREIGN KEY (`tb_boards_bid`)
    REFERENCES `unjarall_db`.`tb_boards` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_comment_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_comment_likes` (
  `clid` INT NOT NULL AUTO_INCREMENT,
  `cnt` INT NULL DEFAULT 0,
  `tb_comments_cid` INT NOT NULL,
  PRIMARY KEY (`clid`),
  INDEX `fk_tb_comment_likes_tb_comments1_idx` (`tb_comments_cid` ASC),
  CONSTRAINT `fk_tb_comment_likes_tb_comments1`
    FOREIGN KEY (`tb_comments_cid`)
    REFERENCES `unjarall_db`.`tb_comments` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_comment_dislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_comment_dislikes` (
  `cdid` INT NOT NULL AUTO_INCREMENT,
  `cnt` INT NULL DEFAULT 0,
  `tb_comments_cid` INT NOT NULL,
  PRIMARY KEY (`cdid`),
  INDEX `fk_tb_comment_dislikes_tb_comments1_idx` (`tb_comments_cid` ASC),
  CONSTRAINT `fk_tb_comment_dislikes_tb_comments1`
    FOREIGN KEY (`tb_comments_cid`)
    REFERENCES `unjarall_db`.`tb_comments` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_team_dislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_team_dislikes` (
  `tdid` INT NOT NULL AUTO_INCREMENT,
  `cnt` INT NULL DEFAULT 0,
  `tb_teams_tid` INT NOT NULL,
  PRIMARY KEY (`tdid`),
  INDEX `fk_tb_team_dislikes_tb_teams1_idx` (`tb_teams_tid` ASC),
  CONSTRAINT `fk_tb_team_dislikes_tb_teams1`
    FOREIGN KEY (`tb_teams_tid`)
    REFERENCES `unjarall_db`.`tb_teams` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_player_dislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_player_dislikes` (
  `pdid` INT NOT NULL AUTO_INCREMENT,
  `cnt` INT NULL DEFAULT 0,
  `tb_players_pid` INT NOT NULL,
  PRIMARY KEY (`pdid`),
  INDEX `fk_tb_player_dislikes_tb_players1_idx` (`tb_players_pid` ASC),
  CONSTRAINT `fk_tb_player_dislikes_tb_players1`
    FOREIGN KEY (`tb_players_pid`)
    REFERENCES `unjarall_db`.`tb_players` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_epl_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_epl_stats` (
  `epl_id` INT NOT NULL AUTO_INCREMENT,
  `tb_stats_sid` INT NOT NULL,
  `crosses` INT NULL DEFAULT 0,
  `yellow` INT NULL DEFAULT 0,
  `red` INT NULL DEFAULT 0,
  `wins` INT NULL DEFAULT 0,
  `losses` INT NULL DEFAULT 0,
  `freekicks` INT NULL DEFAULT 0,
  `penalties` INT NULL DEFAULT 0,
  PRIMARY KEY (`epl_id`),
  INDEX `fk_tb_epl_stats_tb_stats1_idx` (`tb_stats_sid` ASC),
  CONSTRAINT `fk_tb_epl_stats_tb_stats1`
    FOREIGN KEY (`tb_stats_sid`)
    REFERENCES `unjarall_db`.`tb_stats` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_ligue1_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_ligue1_stats` (
  `ligue1_id` INT NOT NULL AUTO_INCREMENT,
  `tb_stats_sid` INT NOT NULL,
  `freekicks` INT NULL DEFAULT 0,
  `minutes` INT NULL DEFAULT 0,
  `penalties` INT NULL DEFAULT 0,
  PRIMARY KEY (`ligue1_id`),
  INDEX `fk_tb_ligue1_stats_tb_stats1_idx` (`tb_stats_sid` ASC),
  CONSTRAINT `fk_tb_ligue1_stats_tb_stats1`
    FOREIGN KEY (`tb_stats_sid`)
    REFERENCES `unjarall_db`.`tb_stats` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_laliga_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_laliga_stats` (
  `laliga_id` INT NOT NULL AUTO_INCREMENT,
  `tb_stats_sid` INT NOT NULL,
  `yellow` INT NULL DEFAULT 0,
  `red` INT NULL DEFAULT 0,
  `penalties` INT NULL DEFAULT 0,
  `fouls` INT NULL DEFAULT 0,
  PRIMARY KEY (`laliga_id`),
  INDEX `fk_tb_laliga_stats_tb_stats1_idx` (`tb_stats_sid` ASC),
  CONSTRAINT `fk_tb_laliga_stats_tb_stats1`
    FOREIGN KEY (`tb_stats_sid`)
    REFERENCES `unjarall_db`.`tb_stats` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_bundes_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_bundes_stats` (
  `bundes_id` INT NOT NULL AUTO_INCREMENT,
  `tb_stats_sid` INT NOT NULL,
  `penalties` INT NULL DEFAULT 0,
  `yellow` INT NULL DEFAULT 0,
  `fouls` INT NULL DEFAULT 0,
  `crosses` INT NULL DEFAULT 0,
  PRIMARY KEY (`bundes_id`),
  INDEX `fk_tb_bundes_stats_tb_stats1_idx` (`tb_stats_sid` ASC),
  CONSTRAINT `fk_tb_bundes_stats_tb_stats1`
    FOREIGN KEY (`tb_stats_sid`)
    REFERENCES `unjarall_db`.`tb_stats` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unjarall_db`.`tb_serie_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unjarall_db`.`tb_serie_stats` (
  `serie_id` INT NOT NULL AUTO_INCREMENT,
  `tb_stats_sid` INT NOT NULL,
  `yellow` INT NULL DEFAULT 0,
  `red` INT NULL DEFAULT 0,
  `penalties` INT NULL DEFAULT 0,
  PRIMARY KEY (`serie_id`),
  INDEX `fk_tb_serie_stats_tb_stats1_idx` (`tb_stats_sid` ASC),
  CONSTRAINT `fk_tb_serie_stats_tb_stats1`
    FOREIGN KEY (`tb_stats_sid`)
    REFERENCES `unjarall_db`.`tb_stats` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
